spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_sim_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # Add this line
    username: root
    password: HARRY123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  jwt:
    secret: AOriIfPEPgGMw8VQiVt/aEoRgL5zjZLqTDR1f7SFuz8=
    expirationMs: 86400000

# ✅ Moved outside spring block
alphavantage:
  api-key: LPGQPD8BXDTRAD4L
  base-url: https://www.alphavantage.co/query
  fetch-interval-ms: 600000

logging:
  level:
    com.stocksim.stocktrading: DEBUG
    org.springframework.security: DEBUG # Keep this for security-related logs